#!/bin/bash

# Event Face CRM - Setup Script
# This script sets up your B2B event services business in 30 days

echo "🚀 Event Face CRM - 30-Day Revenue Setup"
echo "========================================"
echo ""
echo "Goal: $5,000-$14,500 in 30 days"
echo ""

# Check if we're in the right directory
if [ ! -d "linkedin-face-crm" ]; then
    echo "❌ Error: linkedin-face-crm directory not found"
    echo "Please run this script from the directory containing linkedin-face-crm"
    exit 1
fi

echo "📦 Step 1: Installing Instant Face Search Feature..."
echo ""

# Copy the instant search files
cp -f Downloads/files/instant-search-page.tsx linkedin-face-crm/app/search/page.tsx 2>/dev/null || echo "Note: Using existing search page"

# Create components directory if it doesn't exist
mkdir -p linkedin-face-crm/components
cp -f Downloads/files/quick-face-search.tsx linkedin-face-crm/components/QuickFaceSearch.tsx 2>/dev/null || echo "Note: Using existing QuickFaceSearch"

# Create API directory if it doesn't exist
mkdir -p linkedin-face-crm/app/api/face-search
cp -f Downloads/files/face-search-api.ts linkedin-face-crm/app/api/face-search/route.ts 2>/dev/null || echo "Note: Using existing API route"

echo "✅ Instant Face Search feature installed!"
echo ""

echo "🎯 Step 2: Review Your 30-Day Action Plan"
echo "----------------------------------------"
echo ""
echo "Your complete plan is in:"
echo "1. 30_DAY_ACTION_PLAN.md - Week-by-week execution"
echo "2. outreach-scripts.md - Email/LinkedIn templates"
echo "3. INSTANT_SEARCH_SETUP.md - Technical setup guide"
echo "4. README.md - Product overview and strategy"
echo "5. landing-page.html - Ready-to-use landing page"
echo ""

echo "💰 Step 3: Choose Your First Target"
echo "-----------------------------------"
echo ""
echo "Immediate warm leads to contact TODAY:"
echo ""
echo "1. JPMorgan Chase contacts (from Soundraw)"
echo "   - Package: Conference VIP Experience ($2,500-$5,000)"
echo "   - Action: LinkedIn message + email"
echo ""
echo "2. Discord community"
echo "   - Package: Virtual event solution"
echo "   - Action: Discord DM + community post"
echo ""
echo "3. Epic Games connection (GDC - March 17-21)"
echo "   - Package: Trade Show Lead Intelligence ($1,500-$3,000)"
echo "   - Action: Email with GDC-specific proposal"
echo ""
echo "4. VC network (Lux, USV, micro-VCs)"
echo "   - Package: Executive Networking Assistant ($500-$1,000/month)"
echo "   - Action: Personalized email to 5 VCs"
echo ""
echo "5. Podcast network"
echo "   - Package: Executive version with mobile app"
echo "   - Action: Twitter DMs + podcast guest outreach"
echo ""

echo "📊 Step 4: Set Up Tracking"
echo "-------------------------"
echo ""
echo "Recommended tracking setup:"
echo "1. Create Google Sheet for outreach tracking"
echo "2. Set up Calendly for demo bookings"
echo "3. Create simple CRM (Airtable or similar)"
echo "4. Track these metrics daily:"
echo "   - Outreach messages sent"
echo "   - Responses received"
echo "   - Demos booked"
echo "   - Pilots agreed"
echo "   - Revenue closed"
echo ""

echo "🚀 Step 5: Launch Sequence"
echo "-------------------------"
echo ""
echo "Week 1 Checklist (Starting TODAY):"
echo ""
echo "Monday:"
echo "  [ ] Test Instant Face Search feature"
echo "  [ ] Review landing page"
echo "  [ ] Write first 5 outreach messages"
echo ""
echo "Tuesday:"
echo "  [ ] Send 10 LinkedIn messages"
echo "  [ ] Email 5 warm leads"
echo "  [ ] Set up Calendly"
echo ""
echo "Wednesday:"
echo "  [ ] Follow up with contacts"
echo "  [ ] Send 10 new outreach messages"
echo "  [ ] Create demo video"
echo ""
echo "Thursday:"
echo "  [ ] Conduct first demo (if booked)"
echo "  [ ] Send 10 more outreach messages"
echo "  [ ] Create service package PDFs"
echo ""
echo "Friday:"
echo "  [ ] Review week progress"
echo "  [ ] Adjust strategy"
echo "  [ ] Plan Week 2 outreach"
echo "  [ ] Celebrate small wins!"
echo ""

echo "💡 Pro Tips for Success:"
echo "----------------------"
echo "1. Start with WARM leads first (higher response rate)"
echo "2. Offer FREE pilots (removes risk for customers)"
echo "3. Focus on ROI: 'One closed deal pays for 50 events'"
echo "4. Follow up consistently (most sales happen after 5+ touches)"
echo "5. Document everything (for case studies and testimonials)"
echo ""

echo "🎯 Revenue Targets:"
echo "-----------------"
echo "Conservative: $6,000 (2 pilots + 1 subscription)"
echo "Aggressive: $14,500 (1 conference + 3 pilots + 2 subscriptions)"
echo "Stretch: $25,000 (scale after proven success)"
echo ""

echo "📞 Need Help?"
echo "------------"
echo "Remember:"
echo "- After 20 outreach messages with no responses → refine pitch"
echo "- During your first demo → practice makes perfect"
echo "- When you get pricing objections → focus on ROI"
echo "- Before major product changes → validate with customers"
echo ""

echo "🏁 Final Step: Take Action NOW"
echo "-----------------------------"
echo ""
echo "Your next 5 actions (do these TODAY):"
echo ""
echo "1. Open landing-page.html in browser"
echo "2. Pick 3 warm leads to contact"
echo "3. Write personalized messages using outreach-scripts.md"
echo "4. Send those 3 messages NOW"
echo "5. Set reminder to follow up in 2 days"
echo ""
echo "Remember: 30 days from now, you could have $5,000-$14,500 in revenue"
echo "OR you could have regret for not trying."
echo ""
echo "The choice is yours. Start NOW. 🚀"
echo ""
echo "Good luck! You've got this!"
echo ""

# Make the script executable
chmod +x "$0"

echo "Setup complete! Review the files in the event-face-crm directory."
echo "Then run: cd linkedin-face-crm && npm run dev"
echo "To test your Instant Face Search feature at: http://localhost:3000/search"